version: "3.7"
services:
  database:
    image: postgis/postgis:14-3.2
    restart: always
    user: postgres
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 60s
      retries: 5
      start_period: 1s  
    ports:
       - "5414:5432"
    environment:
      POSTGRES_DB: panorama
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: insecure
    command: ["postgres", "-c", "log_statement=all"]

  web:
    build: ./web
    ports:
      - "8087:8000"
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    environment:
      SECRET_KEY: insecure
      DATABASE_PORT: 5414
      DATABASE_NAME: panorama
      DATABASE_USER: postgres
      DB_PASSWORD: insecure
      PANORAMA_IMAGE_URL: https://acc.panorama.data.amsterdam.nl/panorama
      OBJECTSTORE_USER:
      OBJECTSTORE_PASSWORD:
      PANORAMA_TENANT_ID:
      DATAPUNT_TENANT_ID:
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "panorama.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/panorama/static=/static"
      UWSGI_DIE_ON_TERM: 1

  demo:
    build: ./demo
    ports:
      - "8088:80"
    volumes:
      - "./demo/html:/var/www/html/demo"
      - "./test_output:/var/www/html/img"
